[project]
name = "sqlafilters"
version = "0.1.0"
description = "Filtering mixin for SQLAlchemy"
readme = "README.md"
license = "BSD-3-Clause-Clear"
authors = [
    { name = "Elias Gabriel", email = "oss@eliasfgabriel.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2",
    "sqlalchemy>=2,<2.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0",
    "pytest-cov",
    "pytest-crap",
]
local = [
    "ty",
    "prek"
]

[tool.pytest.ini_options]
strict = true
addopts = "-ra -vv --crap --cov sqlafilters --import-mode=importlib"
testpaths = ["tests"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_also = ["if TYPE_CHECKING:"]

[tool.ty.rules]
missing-type-argument = "error"
possibly-unresolved-reference = "warn"

[tool.ruff]
unsafe-fixes = false
extend-include = ["*.md"]

[tool.ruff.lint]
extend-select = ["ANN", "ASYNC", "PYI", "PT", "SIM", "TID", "PERF", "TRY"]
extend-ignore = ["TID252", "TRY003"]
preview = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true
preview = true

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"
