[project]
name = "filtrate"
version = "0.1.0"
description = "Build reusable, composable filters for declarative SQLAlchemy models"
readme = "README.md"
license = "BSD-3-Clause-Clear"
authors = [
    { name = "Elias Gabriel", email = "oss@eliasfgabriel.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed"
]
keywords = ["typed", "database", "orm", "sqlalchemy", "filtering", "filters"]
requires-python = ">=3.14"
dependencies = [
    "beartype>=0.23.0rc0,<1",
    "sqlalchemy>=2,<2.1",
]

[project.urls]
Homepage = "https://github.com/thearchitector/filtrate"
Repository = "https://github.com/thearchitector/filtrate.git"
Issues = "https://github.com/thearchitector/filtrate/issues"

[dependency-groups]
dev = [
    "pytest>=9.0",
    "pytest-cov",
    "pytest-crap",
]
local = [
    "prek",
    "mypy",
]

[tool.pytest.ini_options]
strict = true
addopts = "-ra -vv --crap --cov filtrate --import-mode=importlib"
testpaths = ["tests"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_also = ["TYPE_CHECKING", "NotImplementedError"]

[tool.ruff]
unsafe-fixes = false

[tool.ruff.lint]
extend-select = ["ANN", "ASYNC", "PYI", "PT", "SIM", "TID", "PERF", "TRY", "PGH003"]
extend-ignore = ["TID252", "TRY003"]
preview = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.ruff.format]
docstring-code-format = true
skip-magic-trailing-comma = true
preview = true

[tool.mypy]
strict = true

[tool.ty.rules]
blanket-ignore-comment = "error"
missing-type-argument = "error"
possibly-unresolved-reference = "warn"
unsupported-dynamic-base = "warn"

[tool.ty.analysis]
strict-literal-narrowing = true
strict-generic-narrowing = true

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
